CREATE TABLE IF NOT EXISTS faction_ban (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  faction_id VARCHAR(36) NOT NULL,
  banner_id VARCHAR(36) NOT NULL,
  banned_id VARCHAR(36) NOT NULL,
  banned_at BIGINT NOT NULL
)