CREATE TABLE IF NOT EXISTS faction_home (
  faction_id VARCHAR(36) NOT NULL PRIMARY KEY,
  world_name VARCHAR (255) NOT NULL,
  x DOUBLE NOT NULL,
  y DOUBLE NOT NULL,
  z DOUBLE NOT NULL,
  yaw FLOAT NOT NULL,
  pitch FLOAT NOT NULL
)